[functions]
node_bundler = "esbuild"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[context.deploy-preview]
  command = "pnpm build --configuration staging"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
