[[redirects]]
from = "/api/*"
to = "${API_ORIGIN}/:splat"
status = 301

[context.branch-deploy]
command = "pnpm build --configuration staging"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
